####
#Classpath and file-based solution
####

server:
  port: 8888
management: 
  context-path: /admin
   
eureka: 
  instance: 
    leaseRenewalIntervalInSeconds: 10 
    statusPageUrlPath: /admin/info 
    healthCheckUrlPath: /admin/health 

spring:
  cloud:
    config:
      discovery:
        enabled: true
      server:
        native:
          searchLocations: classpath:config/,classpath:config/account-service,classpath:config/customer-service,classpath:config/PublisherSrv,classpath:config/PublisherSrvPlainText,classpath:config/publisher-service
  profiles:
    active: native
  